# Generated by Django 5.2.6 on 2025-09-21 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_cart_amount_paid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderItem',
            new_name='CartItem',
        ),
    ]
