# Generated by Django 5.2.6 on 2025-09-21 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0003_rename_orderitem_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='amount_paid',
        ),
    ]
